import { Quicksand } from "next/font/google";
import "./globals.css";
import AnnounceBar from "./components/announceBar";
import NavBarOne from "./components/navBarOne";
import NavBarTwo from "./components/navBarTwo";
import Footer from "./components/footer";

const quicksand = Quicksand({ subsets: ["latin"] });

export const metadata = {
  title: "Sankamithra | Fireworks",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={quicksand.className}>
        <AnnounceBar />
        <NavBarOne />
        <NavBarTwo />
        {children}
        <Footer />
      </body>
    </html>
  );
}
